name: goltens_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  goltens_core:
    path: ../goltens_core
  audioplayers: ^6.5.1
  camera: ^0.11.2
  collection: ^1.19.1
  date_time_format: ^2.0.1
  digital_signature_flutter: ^0.0.3
  dio: ^5.9.0
  dropdown_textfield: ^1.2.0
  email_validator: ^3.0.0
  excel: ^4.0.6
  file_picker: ^10.3.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_chat_bubble: ^2.0.2
  floating_action_bubble: ^1.1.4
  flutter_dotenv: ^6.0.0
  flutter_downloader: ^1.12.0
  flutter_email_sender: ^7.0.0
  flutter_riverpod: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_pdfview: ^1.4.1+1
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.1
  http: ^1.5.0
  image_cropper: ^9.1.0
  image_picker: ^1.2.0
  internet_connection_checker: ^3.0.1
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  lottie: ^3.3.0
  mailer: ^6.5.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  printing: ^5.14.2
  provider: ^6.1.5+1
  responsive_framework: ^1.5.1
  roundcheckbox: ^2.0.5
  searchbar_animation: ^0.0.4
  share_plus: ^12.0.0
  time_picker_spinner_pop_up: ^1.5.0
  touch_ripple_effect: ^2.5.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  video_player: ^2.10.0
  videosdk: ^2.2.0
  window_manager: ^0.5.1
  onesignal_flutter: ^5.3.4
  flutter_cached_pdfview: ^0.4.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/
    - .env
